### ISSUE TITLE
[FORG0001] Cannot cast to xs:float: undefined

### ISSUE THREAD

**Issue by kumy** [GeoKretyMap/gkm-api-php#8]
From mail:

`https://api.geokretymap.org/geojson?latTL=45.668331942446045&lonTL=4.157699812503082&latBR=45.848188057553955&lonBR=undefined&limit=500&daysFrom=0&daysTo=-1`

```
<br />
<b>Fatal error</b>:  Uncaught Exception: [FORG0001] Cannot cast to xs:float: undefined. in /var/www/html/lib/BaseXClient.php:185
Stack trace:
#0 /var/www/html/lib/BaseXClient.php(136): Query-&gt;exec('\x03', '0\x00lonBR\x00undefin...')
#1 /var/www/html/geojson.php(18): Query-&gt;bind('lonBR', 'undefined', 'xs:float')
#2 {main}
  thrown in <b>/var/www/html/lib/BaseXClient.php</b> on line <b>185</b><br />
```

**Comment by kumy** [comment]
It's normal to not cast `undefined` to `float`, however, displaying php error is a bad practice in production.

I've disabled error reporting, now such request return a 500 server internal error. I would be better in this case to return a 400, to indicate clients, that they have send a bad request.
